export const AdminActionTypes = {
    SET_ADMIN_USERS: 'admin/SET_ADMIN_USERS',
    SET_LOADING_ADMIN_USERS: 'admin/SET_LOADING_ADMIN_USERS',

    SET_USERS_SEARCH_RESULTS: 'admin/SET_USERS_SEARCH_RESULTS',
    CLEAR_USERS_SEARCH_RESUTLS: 'admin/CLEAR_USERS_SEARCH_RESULTS',
    SET_LOADING_USERS_SEARCH_RESULTS: 'admin/SET_LOADING_USERS_SEARCH_RESULTS',

    SET_BUG_REPORTS_DATA: 'admin/SET_BUG_REPORTS_DATA',
    ADD_BUG_REPORTS_DATA: 'admin/ADD_BUG_REPORTS_DATA',
    SET_LOADING_BUG_REPORTS: 'admin/SET_LOADING_BUG_REPORTS',
    SET_LOADING_BUG_REPORTS_FIRST_PAGE: 'admin/SET_LOADING_BUG_REPORTS_FIRST_PAGE',
    DELETE_BUG_REPORTS: 'admin/DELETE_BUG_REPORTS',
    UPDATE_BUG_REPORTS: 'admin/UPDATE_BUG_REPORTS'
}