export const AdminActionTypes = {
    SET_ADMIN_USERS: 'admin/SET_ADMIN_USERS',
    SET_LOADING_ADMIN_USERS: 'admin/SET_LOADING_ADMIN_USERS',
    SET_USERS_SEARCH_RESULTS: 'admin/SET_USERS_SEARCH_RESULTS',
    CLEAR_USERS_SEARCH_RESUTLS: 'admin/CLEAR_USERS_SEARCH_RESULTS',
    SET_LOADING_USERS_SEARCH_RESULTS: 'admin/SET_LOADING_USERS_SEARCH_RESULTS',
}