export const UserActionTypes = {
    SET_MONGO_USER: 'user/SET_MONGO_USER',
    UPDATE_MONGO_USER: 'user/UPDATE_MONGO_USER',
    CLEAR_USER: 'user/CLEAR_USER',
    SET_LOADING_MONGO_USER: 'user/LOADING_MONGO_USER',
    SET_LOADING_PROFILE_UPDATE: '/user/LOADING_PROFILE_UPDATE',
}